---
- hosts: all
  become: true
  pre_tasks:
    
    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install updates (RedHat)
      tags: always
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "RedHat"

    - name: "Onboard Linux Servers to Azure Arc-enabled servers with Public endpoint connectivity"
      hosts: all
      vars:
        azure:
          service_principal_id: 'd2aabe97-cd1c-4b67-878c-9e28bcde9fb7'
          service_principal_secret: 'rOc8Q~pm-r1ZSzBkXPrcTLEthw7aJqDeZYARWaS0'
          resource_group: 'Arc-Deployment-WorkSpace-RG'
          tenant_id: '73822aac-4c17-4084-be61-b136b7d6de26'
          subscription_id: 'd81b8ec3-8529-485c-984e-34182260d492'
          location: 'eastus'

- hosts: web_servers
  become: true
  tasks:

    - name: Install Apache and PHP for Ubuntu Servers
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install PHP and Apache for RedHat Server 
      tags: apache,redhat,httpd
      dnf:
        name:
          - httpd 
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: start httpd (RedHat)
      tags: apache,redhat,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    # - name: Copy default html file for site
    #   tags: apache,apache2,httpd
    #   copy:
    #     src: default_site.html
    #     dest: /var/www/html/index.html
    #     owner: root
    #     group: root
    #     mode: 0644

- hosts: all
  become: true
  tasks:       

    - name: Create User mofe
      tags: always
      user:
        name: mofe
        groups: root

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: mofe
        key: "{{ lookup('file', '/home/madesanya/.ssh/Ansible.pub') }}"
        state: present

    - name: add sudoer file for mofe
      tags: always
      copy:
        src: /home/madesanya/Documents/Ansible-Automation/files/sudoer_mofe
        dest: /etc/sudoers.d/mofe
        owner: root
        group: root
        mode: 0440

- hosts: workstation
  become: true
  tasks:
    
    - name: Install unzip
      package:
        name: unzip
    
    - name: Install terraform on workstation
      tags: terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0775
        owner: root
        group: root
      

