
- name: Install Apache and PHP for Ubuntu Servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install PHP and Apache for RedHat Server 
  tags: apache,redhat,httpd
  dnf:
    name:
      - httpd 
      - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: start httpd (RedHat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"
